import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import { Container, Form, Input, InputGroup, InputGroupText } from 'reactstrap';
import CurrencySelector2 from '@/components/CurrencySelector2';
import { useEffect, useState } from 'react';
import currencyService, { Currency } from '@/services/currencyService';

const inter = Inter({ subsets: ['latin'] });

const BASE_URL = 'localhost:3000';

export default function Home() {
  const [currencyList, setCurrencyList] = useState<Currency[]>();
  const [fromCurrencyIndex, setFromCurrencyIndex] = useState(0);
  const [toCurrencyIndex, setToCurrencyIndex] = useState(1);

  const height = '400px';
  const getCurrencies = async function () {
    const res = await currencyService.getCurrencies();
    if (res.length > 0) {
      setCurrencyList(res);
    }
  };

  useEffect(() => {
    getCurrencies();
  }, []);

  if (!currencyList) {
    return (
      <>
        <h1>Loading</h1>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Currency Converter</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap"
            rel="stylesheet"
          />
        </Head>
        <main className={styles.main}>
          <Container
            className={styles.container}
            style={{ height: `${height}` }}
          >
            <p className={styles.loggedStatus}>Not Logged</p>
            <p className={styles.appTitle}>Currency Converter</p>
            <div className={styles.inputs}>
              <div className={styles.inputSection}>
                <InputGroup className={styles.valueBox}>
                  <InputGroupText className={styles.moneySymbol}>
                    $
                  </InputGroupText>
                  <Input
                    type="number"
                    className={`form-control ${styles.inputValue}`}
                    aria-label="Username"
                    aria-describedby="basic-addon1"
                  />
                </InputGroup>
                <div className={styles.customSelect}>
                  <Form id="currencySelectorFrom">
                    <CurrencySelector2
                      currencyList={currencyList}
                      selectedCurrencyIndex={fromCurrencyIndex}
                      onChangeCurrency={(e: any) => {
                        const findCurrencyAndReturnIndex =
                          currencyList.findIndex(
                            (currency) =>
                              currency.id === parseFloat(e.target.value)
                          );
                        setFromCurrencyIndex(findCurrencyAndReturnIndex);
                      }}
                    />
                  </Form>
                </div>
              </div>
              <img
                src="/arrow-left-right-white.svg"
                className={styles.switchImage}
                alt=""
              />
              <div className={styles.inputSection}>
                <InputGroup className={styles.valueBox}>
                  <InputGroupText className={styles.moneySymbol}>
                    $
                  </InputGroupText>
                  <Input
                    type="number"
                    className={`form-control ${styles.inputValue}`}
                    aria-label="Username"
                    aria-describedby="basic-addon1"
                  />
                </InputGroup>

                <div className={styles.customSelect}>
                  <Form id="currencySelectorTo">
                    <CurrencySelector2
                      currencyList={currencyList}
                      selectedCurrencyIndex={toCurrencyIndex}
                      onChangeCurrency={(e: any) => {
                        const findCurrencyAndReturnIndex =
                          currencyList.findIndex(
                            (currency) =>
                              currency.id === parseFloat(e.target.value)
                          );
                        setToCurrencyIndex(findCurrencyAndReturnIndex);
                      }}
                    />
                  </Form>
                </div>
              </div>
            </div>
          </Container>
        </main>
      </>
    );
  }
}
