import LoggedStatus from '@/components/LoggedStatus';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { Button, Container } from 'reactstrap';
import styles from '../styles/Home.module.scss';

export default function logout() {
  const height = '260px';

  const router = useRouter();
  const handleReturnToHome = async () => {
    router.push('/');
  };
  const handleLogOut = async () => {
    sessionStorage.clear();
    router.push('/');
    router.push({
      pathname: '/',
      query: { successLogOut: 'true' },
    });
  };
  return (
    <>
      <Head>
        <title>Currency Converter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
        <Container className={styles.container} style={{ height: `${height}` }}>
          <LoggedStatus logged={true} />
          <p className={styles.appTitle}>Currency Converter</p>
          <div className={styles.pageContent}>
            <section
              className={styles.buttonsSection}
              style={{ marginTop: `28px`, flexDirection: `column` }}
            >
              <Button className={styles.button} onClick={handleLogOut}>
                Log out
              </Button>
              <Button className={styles.button} onClick={handleReturnToHome}>
                Return to Home
              </Button>
            </section>
          </div>
        </Container>
      </main>
    </>
  );
}
