import Head from 'next/head';
import React from 'react';
import { Button, Container, Form, Input } from 'reactstrap';
import styles from '@/styles/Home.module.scss';
import registerStyles from '../styles/register.module.scss';

export default function register() {
  const height = '600px';
  return (
    <>
      <Head>
        <title>Currency Converter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
        <Container className={styles.container} style={{ height: `${height}` }}>
          <p className={styles.loggedStatus}>Not Logged</p>
          <p className={styles.appTitle}>Currency Converter</p>
          <div className={styles.pageContent}>
            <Form className={registerStyles.form}>
              <Input
                type="text"
                className={registerStyles.input}
                placeholder="First Name"
              ></Input>
              <Input
                type="text"
                className={registerStyles.input}
                placeholder="Email"
              ></Input>
              <Input
                type="text"
                className={registerStyles.input}
                placeholder="Password"
              ></Input>
              <Input
                type="text"
                className={registerStyles.input}
                placeholder="Confirm Password"
              ></Input>
              <Button type="submit" className={styles.button}>
                Create Account
              </Button>
            </Form>
            <section className={styles.buttonsSection}>
              <Button className={styles.button}>Return to Home</Button>
              <Button className={styles.button}>Go to Login</Button>
            </section>
          </div>
        </Container>
      </main>
    </>
  );
}
